name: 'Prepare project'
description: 'Checks out code and installs dependencies.'

runs:
    using: 'composite'
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
              fetch-depth: 0

        - name: Install node and pnpm
          uses: ./.github/actions/setup-node-and-pnpm/

        - name: Install dependencies
          run: pnpm install --frozen-lockfile
          shell: bash

        - name: Upload Prepared Repository Artifact
          uses: actions/upload-artifact@v4
          with:
              name: prepared-repository
              path: .
